In [5]:
import numpy as np

Boolean Indexing

In [6]:
arr = np.array([10,20,30,40,50])

In [7]:
mask = arr > 25

In [9]:
print(mask)

[False False  True  True  True]


In [10]:
print(arr[mask])

[30 40 50]


Boolean Indexing with Conditions

In [11]:
arr = np.array([1,2,3,4,5,5,6,7,8,9,0,12])

In [12]:
print(arr)

[ 1  2  3  4  5  5  6  7  8  9  0 12]


In [13]:
print(arr[arr % 2 == 0])

[ 2  4  6  8  0 12]


In [15]:
arr = np.array([10,34,54,67,90,86,20,53,100,106,115])
arr

array([ 10,  34,  54,  67,  90,  86,  20,  53, 100, 106, 115])

In [17]:
print(arr[(arr > 20 ) & (arr<100)])

[34 54 67 90 86 53]


In [18]:
print(arr[(arr < 20) | (arr > 40)])

[ 10  54  67  90  86  53 100 106 115]


In [21]:
not_Zero = arr[~(arr == 0)]
print(not_Zero)

[ 10  34  54  67  90  86  20  53 100 106 115]


Task 1.4.1: Given a 6×6 matrix of random integers 1–100, extract all elements that are divisible by
both 3 and 5.

In [26]:
arr = np.random.randint(1,101,size = (6,6))

In [27]:
arr

array([[42,  5, 73, 34, 57, 73],
       [84, 99, 50, 85,  2, 28],
       [27, 58, 18, 69,  6, 97],
       [13, 52, 60, 42, 75, 73],
       [64, 48, 45, 78, 23, 70],
       [75, 72, 55, 28,  5, 17]], dtype=int32)

In [29]:
result = arr[(arr % 3 == 0) & (arr % 5 == 0)]
print(result)

[60 75 45 75]


Task 1.4.2: Use np.where to replace all values below the mean of an array with 0 and above with 1
(binarise).

In [30]:
arr = np.array([10, 25, 40, 55, 70, 85])

In [31]:
arr

array([10, 25, 40, 55, 70, 85])

In [32]:
mean_value = np.mean(arr)

In [33]:
mean_value

np.float64(47.5)

In [34]:
binary_arr = np.where(arr < mean_value , 0 ,1)

In [35]:
binary_arr

array([0, 0, 0, 1, 1, 1])

Task 1.4.3: Use np.ix_ to extract a 3×3 sub-matrix from rows [1,3,4] and columns [0,2,4] of a 5×5
array.

In [39]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
rows =  [1,3,4]
cols =  [0,2,4]
sub_matrix = arr[np.ix_(rows , cols)]
sub_matrix

array([[ 6,  8, 10],
       [16, 18, 20],
       [21, 23, 25]])

 Task 1.4.4: Sort a 4×4 random matrix row-wise and column-wise separately (without loops).

In [43]:
arr = np.random.randint(1,100,size = (4,4))
arr

array([[52,  2, 62,  3],
       [85, 10, 98, 75],
       [86,  4, 44, 58],
       [45, 22, 21, 38]], dtype=int32)

In [45]:
row_sort = np.sort(arr,axis = 1)
row_sort

array([[ 2,  3, 52, 62],
       [10, 75, 85, 98],
       [ 4, 44, 58, 86],
       [21, 22, 38, 45]], dtype=int32)

In [46]:
col_sort = np.sort(arr,axis=0)
col_sort

array([[45,  2, 21,  3],
       [52,  4, 44, 38],
       [85, 10, 62, 58],
       [86, 22, 98, 75]], dtype=int32)

Task 1.4.5: Use np.select to classify 15 random scores into: 'A'(≥85), 'B'(≥70), 'C'(≥55), 'D'(≥40),
'F'(below 40).

In [53]:
scores = np.random.randint(0,101,15)

In [54]:
scores

array([ 26,  56, 100,  62,  59,  57,  85,   8,  63,  91,  72,  96,  31,
        41,  84], dtype=int32)

In [55]:
conditions = [
    scores >= 85,
    scores >= 70,
    scores >= 55,
    scores >= 40
]
grades = ['A','B','C','D']

In [56]:
result = np.select(conditions,grades,default='F')
result

array(['F', 'C', 'A', 'C', 'C', 'C', 'A', 'F', 'C', 'A', 'B', 'A', 'F',
       'D', 'B'], dtype='<U1')

Broadcasting — Deep Dive

Task 2.2.1: Without loops, add [1, 2, 3, 4] to every row of a (5,4) matrix and subtract [10,20,30,40,50]
from every column.

In [58]:
arr = np.random.randint(1,100 , size=(5,4))
arr

array([[82, 99, 16, 97],
       [34, 14, 25, 43],
       [91, 11, 47, 63],
       [86, 15, 52, 71],
       [85, 43, 27, 10]], dtype=int32)

In [60]:
row_add = arr + np.array([1,2,3,4])
row_add

array([[ 83, 101,  19, 101],
       [ 35,  16,  28,  47],
       [ 92,  13,  50,  67],
       [ 87,  17,  55,  75],
       [ 86,  45,  30,  14]])

In [63]:
col_sub = row_add - np.array([10,20,30,40,50]).reshape(5,1)
col_sub

array([[ 73,  91,   9,  91],
       [ 15,  -4,   8,  27],
       [ 62, -17,  20,  37],
       [ 47, -23,  15,  35],
       [ 36,  -5, -20, -36]])

Task 2.2.2: Normalise each column of a 6×4 random matrix to have mean=0 and std=1 using
broadcasting.

In [66]:
arr = np.random.randint(1,100,size=(6,4))
arr

array([[24, 11, 97, 20],
       [16, 30, 35, 82],
       [57, 20, 93, 59],
       [17, 38, 87, 33],
       [18, 36, 67,  3],
       [18,  2, 34, 80]], dtype=int32)

In [67]:
mean_val = np.mean(arr,axis = 0)

In [68]:
mean_val

array([25.        , 22.83333333, 68.83333333, 46.16666667])

In [69]:
std = np.std(arr,axis=0)

In [70]:
std

array([14.53730832, 13.14555269, 26.04109999, 29.76248571])

In [72]:
normalize = (arr - mean_val )/std

In [73]:
normalize

array([[-0.06878853, -0.9001777 ,  1.08162354, -0.87918284],
       [-0.61909673,  0.54517804, -1.29922827,  1.2039765 ],
       [ 2.20123281, -0.2155355 ,  0.92802019,  0.43119158],
       [-0.5503082 ,  1.15374888,  0.69761518, -0.44239136],
       [-0.48151968,  1.00160617, -0.07040153, -1.45037169],
       [-0.48151968, -1.58481989, -1.33762911,  1.13677781]])

 Task 2.2.3: Build a distance matrix: given 5 points on a number line, create a 5×5 matrix where entry
[i,j] = |points[i] - points[j]|. Use broadcasting, no loops

In [75]:
points = np.array([2, 5, 9, 14, 20])

In [76]:
distance_matrix = np.abs(points[:, np.newaxis] - points)

In [77]:
distance_matrix

array([[ 0,  3,  7, 12, 18],
       [ 3,  0,  4,  9, 15],
       [ 7,  4,  0,  5, 11],
       [12,  9,  5,  0,  6],
       [18, 15, 11,  6,  0]])

In [78]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [79]:
A

array([[1, 2],
       [3, 4]])

In [80]:
B

array([[5, 6],
       [7, 8]])

In [82]:
np.dot(A , B)

array([[19, 22],
       [43, 50]])

In [83]:
print(A@B)

[[19 22]
 [43 50]]


In [86]:
A = np.array([[2,1],[1,3]])
A

array([[2, 1],
       [1, 3]])

In [87]:
Ai = np.linalg.inv(A)
print(Ai)

[[ 0.6 -0.2]
 [-0.2  0.4]]


In [88]:
print(A @ Ai)

[[ 1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00]]


In [90]:
print(np.linalg.det(A))

5.000000000000001


In [92]:
vals , vecs = np.linalg.eig(A)
print(vals) # eigenvalues
print(vecs)  # eigenvectore

[1.38196601 3.61803399]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


Task 3.3.1: Create a random 3×3 matrix A. Verify A @ inv(A) ≈ identity using np.allclose.

In [94]:
S = np.random.randint(1,26, size = (3,3))

In [95]:
S

array([[ 5, 12,  5],
       [23, 25, 16],
       [24,  1, 24]], dtype=int32)

In [96]:
Si = np.linalg.inv(S)
Si

array([[-2.94800606e-01,  1.42857143e-01, -3.38213024e-02],
       [ 8.48056537e-02,  4.78283749e-18, -1.76678445e-02],
       [ 2.91267037e-01, -1.42857143e-01,  7.62241292e-02]])

In [97]:
S @ Si

array([[ 1.00000000e+00, -8.32667268e-17, -1.38777878e-17],
       [-8.88178420e-16,  1.00000000e+00,  2.22044605e-16],
       [ 4.44089210e-16, -6.66133815e-16,  1.00000000e+00]])

Task 3.3.2: Solve the system: 2x+y=5, x+3y=10 using np.linalg.solve. Verify your answer.

In [98]:
X = np.array([[2,1],[1,3]])
X

array([[2, 1],
       [1, 3]])

In [99]:
Y = np.array([5,10])
Y

array([ 5, 10])

In [100]:
sol = np.linalg.solve(X,Y)

In [101]:
sol

array([1., 3.])

Task 3.3.3: Generate a symmetric matrix S = A.T @ A. Compute its eigenvalues and verify they are all
non-negative.

In [102]:
A = np.random.randint(1,10,size = (3,3))
A

array([[9, 2, 5],
       [5, 6, 6],
       [8, 3, 1]], dtype=int32)

In [103]:
S = A.T @ A

In [104]:
S

array([[170,  72,  83],
       [ 72,  49,  49],
       [ 83,  49,  62]], dtype=int32)

In [108]:
eigenvalue = np.linalg.eigvals(S)
eigenvalue

array([252.05709051,  22.87910362,   6.06380587])

In [110]:
print(np.all(eigenvalue >= 0))

True


Task 3.3.4: Compute the dot product of two random unit vectors (normalise with np.linalg.norm
first). Interpret the result

In [111]:
v1 = np.random.randint(1, 10, size=3)
v2 = np.random.randint(1, 10, size=3)

In [112]:
u1 = v1 / np.linalg.norm(v1)
u2 = v2 / np.linalg.norm(v2)

In [113]:
dot_product = np.dot(u1, u2)

In [114]:
dot_product

np.float64(0.7295965065922014)

Sorting, Searching & Set Operations

Task 4.3.1: Given a 1D array of 20 random integers, find the indices of the 5 smallest and 5 largest
values without fully sorting

In [119]:
arr = np.random.randint(1, 100, 20)

In [120]:
smallest_idx = np.argpartition(arr, 5)[:5]
largest_idx = np.argpartition(arr, -5)[-5:]
print(smallest_idx)
print(largest_idx)

[ 4 14 12 13 15]
[ 2  8 17 10  6]


Task 4.3.2: Sort a 5×5 matrix so each row is sorted ascending and each column is sorted ascending
(hint: sort rows first, then columns).


In [122]:
arr = np.random.randint(1, 100, size=(5,5))
row_sorted = np.sort(arr,axis=1)
final_matrix = np.sort(row_sorted,axis=0)

In [123]:
final_matrix

array([[ 2,  2, 27, 59, 85],
       [ 8, 23, 36, 78, 93],
       [11, 30, 40, 80, 98],
       [18, 45, 46, 82, 99],
       [30, 58, 67, 92, 99]], dtype=int32)

Task 4.3.3: From two random integer arrays of size 15 (range 1–20), find common elements,
elements only in A, and elements only in B.

In [124]:
A = np.random.randint(1, 21, 15)
B = np.random.randint(1, 21, 15)

In [125]:
common = np.intersect1d(A, B)

In [126]:
common

array([ 1,  6, 10, 13, 20], dtype=int32)

Comprehensive Challenge Tasks

7.1 Mini Statistics Engine
Write a function stats_report(arr) that accepts a 2D array and prints: shape, min, max, mean, median,
std, 25th and 75th percentile, and the row and column indices of the global maximum.


In [127]:
def stats_report(arr):
    print(arr)

    #shape
    print(arr.shape)

    #min
    print(np.min(arr))

    #maA
    print(np.max(arr))

    #mean
    print(np.mean(arr))

    #medianA
    print(np.median(arr))

    #std
    print(np.std(arr))

    #25th
    print(np.percentile(arr,25))

    #75th
    print(np.percentile(arr,75))

arr = np.random.randint(1,100,size=(4,5))

stats_report(arr)

[[50 42 48 93 88]
 [10 48 25 81 80]
 [73 45 11 65 74]
 [69 13 44 25 52]]
(4, 5)
10
93
51.8
49.0
25.156708846747026
37.75
73.25


7.2 Image as Array
Simulate a grayscale image as a random integer array of shape (100, 100) with values 0–255. (a) Flip it
horizontally and vertically. (b) Crop the centre 40×40 region. (c) Increase brightness by 20 (clip at 255
using np.clip). (d) Threshold: pixels > 128 → 255, rest → 0.

In [130]:
img = np.random.randint(0,256,size=(100,100),dtype=np.uint8)
print(img.shape)
img

(100, 100)


array([[ 78, 241, 123, ...,  65, 130,  18],
       [ 53,  91,  22, ...,  84,  90, 156],
       [232, 250, 127, ...,  73,  69, 242],
       ...,
       [254,  14,  56, ..., 154, 250,  63],
       [101, 242, 249, ..., 245, 198,  92],
       [159,  25, 228, ..., 190, 110,  21]], shape=(100, 100), dtype=uint8)

In [131]:
horizontal_flip = np.fliplr(img)
horizontal_flip

array([[ 18, 130,  65, ..., 123, 241,  78],
       [156,  90,  84, ...,  22,  91,  53],
       [242,  69,  73, ..., 127, 250, 232],
       ...,
       [ 63, 250, 154, ...,  56,  14, 254],
       [ 92, 198, 245, ..., 249, 242, 101],
       [ 21, 110, 190, ..., 228,  25, 159]], shape=(100, 100), dtype=uint8)

In [133]:
vertical_flip = np.flipud(img)
vertical_flip

array([[159,  25, 228, ..., 190, 110,  21],
       [101, 242, 249, ..., 245, 198,  92],
       [254,  14,  56, ..., 154, 250,  63],
       ...,
       [232, 250, 127, ...,  73,  69, 242],
       [ 53,  91,  22, ...,  84,  90, 156],
       [ 78, 241, 123, ...,  65, 130,  18]], shape=(100, 100), dtype=uint8)

In [134]:
center_crop = img[30:70,30:70]
print(center_crop.shape)

(40, 40)


In [135]:
bright_img = np.clip(img + 20, 0, 255)
bright_img

array([[ 98,   5, 143, ...,  85, 150,  38],
       [ 73, 111,  42, ..., 104, 110, 176],
       [252,  14, 147, ...,  93,  89,   6],
       ...,
       [ 18,  34,  76, ..., 174,  14,  83],
       [121,   6,  13, ...,   9, 218, 112],
       [179,  45, 248, ..., 210, 130,  41]], shape=(100, 100), dtype=uint8)

In [136]:
threshold_img = np.where(img > 128, 255, 0)
threshold_img

array([[  0, 255,   0, ...,   0, 255,   0],
       [  0,   0,   0, ...,   0,   0, 255],
       [255, 255,   0, ...,   0,   0, 255],
       ...,
       [255,   0,   0, ..., 255, 255,   0],
       [  0, 255, 255, ..., 255, 255,   0],
       [255,   0, 255, ..., 255,   0,   0]], shape=(100, 100))

7.3 Student Ranking System
Given a 30×5 array of student marks (subjects), compute: (a) overall average per student, (b) rank each
student (1=best), (c) find the top 5 students and bottom 5 students, (d) compute the correlation
between subject 1 and subject 2 scores using np.corrcoef.


In [137]:
marks = np.random.randint(35, 101, size=(30,5))

print("Marks Matrix Shape:")
print(marks.shape)

Marks Matrix Shape:
(30, 5)


In [138]:
average_marks = np.mean(marks,axis = 1)
average_marks

array([69.2, 53.2, 83. , 62. , 60.4, 52.2, 67.4, 64. , 72.2, 57.2, 75. ,
       72.6, 54.4, 72.8, 66.2, 60. , 78.8, 58.8, 67.2, 75.2, 73.2, 72.2,
       65.8, 49.4, 53.2, 75. , 78.2, 51.4, 75.8, 64. ])

In [139]:
sorted_indices = np.argsort(-average_marks)

# Create rank array
ranks = np.empty_like(sorted_indices)

# Assign ranks
ranks[sorted_indices] = np.arange(1, 31)
print(ranks)

[13 27  1 20 21 28 14 18 12 24  7 10 25  9 16 22  2 23 15  5  8 11 17 30
 26  6  3 29  4 19]


In [141]:
top_5 = sorted_indices[:5]
bottom_5 = sorted_indices[-5:]
print(top_5)
bottom_5

[ 2 16 26 28 19]


array([24,  1,  5, 27, 23])

In [142]:
corr_matrix = np.corrcoef(marks[:,0], marks[:,1])

print("\nCorrelation Matrix:\n")
print(corr_matrix)


Correlation Matrix:

[[1.         0.37175482]
 [0.37175482 1.        ]]


7.4 Monte Carlo Pi Estimation
Estimate π using Monte Carlo: generate N=1,000,000 random (x,y) points in [0,1]×[0,1]. Count how many
fall inside the unit circle (x²+y²≤1). π ≈ 4 × (inside/total). Do this entirely with NumPy — no Python loop

In [144]:
import numpy as np


N = 1_000_000


x = np.random.rand(N)
y = np.random.rand(N)


inside = (x**2 + y**2) <= 1

inside_count = np.sum(inside)


pi_estimate = 4 * (inside_count / N)

print("Points Inside Circle:")
print(inside_count)

print("\nEstimated Pi:")
print(pi_estimate)

Points Inside Circle:
784771

Estimated Pi:
3.139084


7.5 Portfolio Risk Analysis
Create a (12, 5) array representing monthly returns of 5 assets over 12 months. Compute: (a) mean
return per asset, (b) covariance matrix using np.cov, (c) portfolio variance for equal weights [0.2]*5, (d)
identify the highest-risk and lowest-risk asset.

In [147]:
returns = np.random.uniform(-0.1, 0.15, size=(12,5))


print(returns.shape)


print(returns)


mean_returns = np.mean(returns, axis=0)


print(mean_returns)

cov_matrix = np.cov(returns, rowvar=False)


print(cov_matrix)


weights = np.array([0.2, 0.2, 0.2, 0.2, 0.2])

portfolio_variance = weights.T @ cov_matrix @ weights


print(portfolio_variance)

asset_variances = np.var(returns, axis=0)

highest_risk = np.argmax(asset_variances)
lowest_risk = np.argmin(asset_variances)


print(asset_variances)


print(highest_risk)


print(lowest_risk)

(12, 5)
[[-0.07391615  0.09465335  0.11157673 -0.03126399  0.02721931]
 [-0.05064269  0.06173512  0.06016843 -0.06255174  0.13512601]
 [-0.08458013 -0.02847963  0.0954267   0.07813672  0.04502743]
 [ 0.0404342   0.11564154  0.03727958  0.13262443  0.12906979]
 [ 0.00596513 -0.09863199  0.13654348  0.01127744  0.0251789 ]
 [ 0.05045582  0.10572365 -0.06439548 -0.02917784  0.12517421]
 [ 0.14854265 -0.03904999  0.14308315  0.10964794  0.10348939]
 [-0.04837643 -0.0436411   0.12529069  0.02952959 -0.04146498]
 [ 0.06623525  0.04970898 -0.05766957  0.09402123  0.12446284]
 [ 0.11338136  0.11715963  0.14252317 -0.07666742  0.02060263]
 [ 0.07974543 -0.03664838  0.14725648 -0.04523321  0.11715187]
 [ 0.11524021  0.11736047  0.03402613  0.06703098  0.046362  ]]
[0.03020705 0.03462764 0.07592579 0.02311451 0.07144995]
[[ 0.00633964  0.00114953 -0.00041982  0.00099637  0.0014332 ]
 [ 0.00114953  0.00620135 -0.00314397 -0.00071507  0.00119448]
 [-0.00041982 -0.00314397  0.00571193 -0.00125755 -0