In [1]:
import numpy as np

In [2]:
import time

Python List

In [3]:
list = [1,2,3,4]
print(list * 2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
print(a.shape)
print(b.shape)
print(b.ndim)
print(b.dtype)

(5,)
(2, 3)
2
int64


Creating Array

In [12]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.arange(0, 10, 2)       

array([0, 2, 4, 6, 8])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.random.rand(3, 3)  

array([[0.50070488, 0.83716546, 0.59235661],
       [0.13447286, 0.50712569, 0.41496485],
       [0.5469841 , 0.59789159, 0.15710489]])

In [21]:
np.random.randint(0, 10, size=(2, 3))  

array([[4, 7, 5],
       [6, 9, 6]], dtype=int32)

Indexing & Slicing

In [22]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])      
print(a[-1])    
print(a[1:4])    
print(a[::2])    

10
50
[20 30 40]
[10 30 50]


In [29]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])     

In [30]:
a+b

array([11, 22, 33, 44])

In [31]:
a * 3

array([ 3,  6,  9, 12])

In [32]:
a ** 2

array([ 1,  4,  9, 16])

In [33]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [28]:
a > 2

array([False, False,  True,  True])

Brodcasting


In [34]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])   

b = np.array([10, 20, 30])  

a + b  

array([[11, 22, 33],
       [14, 25, 36]])

Aggregations


In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a.sum()

np.int64(21)

In [36]:
a.mean()

np.float64(3.5)

In [37]:
a.max()

np.int64(6)

In [38]:
a.min()

np.int64(1)

In [39]:
a.std()

np.float64(1.707825127659933)

In [40]:
a.sum(axis = 0)

array([5, 7, 9])

In [41]:
a.sum(axis=1)

array([ 6, 15])

 Reshaping & Stacking

In [42]:
a = np.arange(12)
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a.reshape(2, -1) 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [44]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Stacking

In [45]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [46]:
np.vstack([x, y])  


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

Boolean Masking 

In [49]:
a = np.array([3, 7, 1, 9, 2, 8])

mask = a > 5         
a[mask] 

array([7, 9, 8])

In [50]:

a[a > 5] = 0   

In [51]:
a

array([3, 0, 1, 0, 2, 0])